### ISSUE TITLE
`GameInfo#getLatestVoteList`が空になってしまっている

### ISSUE THREAD

**Issue by NONONOexe** [aiwolf/AIWolfCommon#4]
Agent側で`currentGameInfo.getVoteList()`と`currentGameInfo.getLatestVoteList()`を各日で出力したところ，`voteList`に出力した日の投票内容が格納されており，latestVoteListの方が空になっていました．

`GameInfo#getVoteList()`は「そのゲームでの投票情報すべてを含むリスト」を返すメソッド，`GameInfo#getLatestVoteList()`は「そのゲームでの最後の（決選投票があった場合は決選投票の）投票情報を含むリスト」を返すメソッドである認識です．

ver.0.6.3で試しましたが，こちらの問題の可能性もあるため，確認してもらえると助かります．
また想定している仕様が正しいかを教えていただけると嬉しいです．

**Comment by AIWolfSharp** [comment]
人狼知能プラットフォームの更新ログにあるように，仕様では

> 2016/12/21 ver0.4.1に更新
> 
> -  vote()で再投票のときに前回の投票状況を知らせるため，GameInfoにlatestVoteListフィールドを追加．このフィールドは当日限り有効（日付変更とともに空になる）で，最終的な投票状況は翌日のGameInfoのvoteListフィールドに入る．

となっています。

> voteListに出力した日の投票内容が格納されており，latestVoteListの方が空になっていました．

とありますが，前日の投票内容ではありませんか。

**Comment by NONONOexe** [comment]
@AIWolfSharp
返信ありがとうございます．
ネーミングから仕様の認識を誤解していました．こちらでログを再確認してみます．

**Comment by NONONOexe** [comment]
すみません，こちらでシミュレーションして，機能していることが確認できましたので，Closeします．
村人だと投票後に翌日になってしまうことでLatestVoteListが空になっていたのを，機能していない
ものと勘違いしていました．
[log.txt](https://github.com/aiwolf/AIWolfCommon/files/11341415/log.txt)
