### ISSUE TITLE
自身のエージェントが死亡している際の再投票時の最初の投票内容について

### ISSUE THREAD

**Issue by puregumi** [aiwolf/AIWolfCommon#5]
対戦中にエージェントの特徴量を取得するために，全エージェント（自分も含む）の投票内容を抽出するプログラムを作成しています．

自身のエージェントが死亡している状態で再投票になった場合の再投票前の全エージェントの投票リストを取得したいのですが，自身のエージェントが死亡している際にその内容を取得する方法が分からず困っています．

自身のエージェントが生きている場合は`talk()`の２回目の呼び出しの時に`getLatestVotelist()`から取得できたのですが，死亡している場合には`talk()`が呼び出されず，翌日の`getVotelist()`からも参照できませんでした．

環境はver.0.6.3です．仕様である可能性もありますが，教えていただけると嬉しいです．

**Comment by AIWolfSharp** [comment]
まず確認ですが，talk()はvote()の書き間違いではありませんか．
ver0.5.4以降の仕様では，死んだエージェントの1日はupdate()とdayStart()の呼び出しで始まり，1日の最後にupdate()が呼ばれて終わります．したがってvote()の前のupdate()は呼ばれないので1回目の投票内容を得ることはできません．

**Comment by puregumi** [comment]
申し訳ありません．vote()の書き間違いでした．
回答ありがとうございます．
